version: '3.8'

services:
  s_svelteapp:
    image: node:18-alpine3.18
    container_name: c_donutsvg
    ports:
      - 3000:3000
    working_dir: /donutsvg
    volumes:
      - ./:/donutsvg
    command: sh -c "npm i && npm run dev"